/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.lanhouse.view;

import br.com.lanhouse.dao.impl.ClienteDAO;
import br.com.lanhouse.dao.impl.ComputadorDAO;
import br.com.lanhouse.dao.impl.UsoDAO;
import br.com.lanhouse.model.equipamento.Computador;
import br.com.lanhouse.model.pessoas.Cliente;
import br.com.lanhouse.model.pessoas.Usuario;
import br.com.lanhouse.model.servicos.Uso;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aluno
 */
public class ViewCriarUso extends javax.swing.JDialog {

    /**
     * Creates new form ViewCriarUso
     */
    public ViewCriarUso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jTextInputLogin = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextValorHora = new javax.swing.JTextField();
        jBtnPesquisar = new javax.swing.JButton();
        jBtnCriarUso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabelNome.setText("Login");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Login"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Computador");

        jLabel2.setText("Valor Hora");

        jTextValorHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextValorHoraActionPerformed(evt);
            }
        });

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        jBtnCriarUso.setText("Criar");
        jBtnCriarUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCriarUsoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNome)
                    .addComponent(jTextInputLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBtnPesquisar)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCriarUso, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNome)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextInputLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextValorHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jBtnCriarUso, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addGap(4, 4, 4)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jBtnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextValorHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextValorHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextValorHoraActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        try {
            ArrayList<Computador> lista = new ComputadorDAO().BuscarTodos();
            preencheCombo(lista);
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao consultar "+ex.getMessage());
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        
        try {
            ArrayList<Cliente> lista = new ClienteDAO().buscaPorLogin(jTextInputLogin.getText());
            preencheTabela(lista);
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao consultar "+ex.getMessage());
        }
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnCriarUsoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCriarUsoActionPerformed
        int selectedRow = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String nome = (String) model.getValueAt(selectedRow, 0);
        String login = (String) model.getValueAt(selectedRow, 1);
           
        if (jTable1.getSelectedRow() < 0){
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }else{
            Cliente c = null;
            
            try {
                ArrayList<Cliente> clientes = new ClienteDAO().buscaPorLogin(login);
                if (!clientes.isEmpty()) {
                    // Considerando que você queira obter apenas o primeiro cliente retornado
                    c = clientes.get(0);
                      
                }
            } catch (SQLException ex) {
                Logger.getLogger(ViewCriarUso.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ViewCriarUso.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (c != null) {
                // Faça algo com o objeto Cliente retornado, por exemplo:
                System.out.println("Cliente encontrado: " + c.getNome());
                Uso uso = new Uso();
                uso.setIdUsuario(c);
                
                int idComputadorSelecionado = (int) jComboBox1.getSelectedItem();
                
                ComputadorDAO computadorDAO = new ComputadorDAO();
                Computador computadorSelecionado = null;
                try {
                    computadorSelecionado = computadorDAO.buscar(idComputadorSelecionado);
                } catch (SQLException ex) {
                    Logger.getLogger(ViewCriarUso.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(ViewCriarUso.class.getName()).log(Level.SEVERE, null, ex);
                }
                 
               
                 if (computadorSelecionado != null) {
                uso.setComputador(computadorSelecionado);
                uso.setValorHora(Double.parseDouble(jTextValorHora.getText()));
                uso.setQtidadeMinutosTempo(60);
                uso.setServico(null);
                uso.setDiaLogin(LocalDateTime.now());

                // Chame o método inserir() do UsoDAO para salvar o novo uso
                UsoDAO usoDAO = new UsoDAO();
                try {
                    usoDAO.inserir(uso);
                    System.out.println("Novo uso criado com sucesso!");
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(ViewCriarUso.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                // Computador não encontrado
                System.out.println("Computador não encontrado.");
            }
        } else {
            // Cliente não encontrado
            System.out.println("Cliente não encontrado.");
        }
            
        }
        
        
    }//GEN-LAST:event_jBtnCriarUsoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCriarUso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCriarUso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCriarUso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCriarUso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewCriarUso dialog = new ViewCriarUso(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCriarUso;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextInputLogin;
    private javax.swing.JTextField jTextValorHora;
    // End of variables declaration//GEN-END:variables

    private void preencheCombo(ArrayList<Computador> lista) {
   
        DefaultComboBoxModel dft = (DefaultComboBoxModel) jComboBox1.getModel();
         dft.removeAllElements();
         for(Computador c :lista){
            dft.addElement(c.getId());
         }
    }
    
    private void preencheTabela(ArrayList<Cliente> lista) throws SQLException, ClassNotFoundException {
        DefaultTableModel dft = (DefaultTableModel) jTable1.getModel();
         while (dft.getRowCount() > 0) {
            dft.removeRow(0);
        }
         
         for(Cliente c :lista){
             String[] linha = {c.getNome(), c.getLogin()};
            dft.addRow(linha);
         }
    }
    
    
    private Usuario user;

    public void getUser(Usuario user) {
        this.user = user;
    }
}
