/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.lanhouse.view;

import br.com.lanhouse.dao.impl.ClienteDAO;
import br.com.lanhouse.dao.impl.ComputadorDAO;
import br.com.lanhouse.dao.impl.ServicoDAO;
import br.com.lanhouse.dao.impl.UsoDAO;
import br.com.lanhouse.model.e.EProduto;
import br.com.lanhouse.model.e.ETipoCliente;
import br.com.lanhouse.model.equipamento.Computador;
import br.com.lanhouse.model.pessoas.Cliente;
import br.com.lanhouse.model.pessoas.Usuario;
import br.com.lanhouse.model.servicos.Servico;
import br.com.lanhouse.model.servicos.Uso;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author paulo
 */
public class ViewSolicitarProduto extends javax.swing.JDialog {
    
    /**
     * Creates new form ViewSolicitarProduto
     */
    public ViewSolicitarProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jBtnSolicitar = new javax.swing.JButton();
        jLabelValorEProduto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Produto");

        jLabel2.setText("Valor");

        jBtnSolicitar.setText("Solicitar");
        jBtnSolicitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSolicitarActionPerformed(evt);
            }
        });

        jLabelValorEProduto.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabelValorEProduto))
                .addGap(75, 75, 75))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jBtnSolicitar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelValorEProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jBtnSolicitar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ArrayList<EProduto> lista = new ArrayList<>();
        lista.add(EProduto.COCA);
        lista.add(EProduto.PEPSI);
        lista.add(EProduto.SALGADO);
        preencheCombo(lista);
        
        if((String)jComboBox1.getSelectedItem()== "Coca"){
            jLabelValorEProduto.setText(""+EProduto.COCA.getValor());
        }
        
       jComboBox1.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent event) {
            String produtoSelecionado = (String) jComboBox1.getSelectedItem();
            EProduto produto = null;
            if (produtoSelecionado.equals("Coca")) {
                produto = EProduto.COCA;
            } else if (produtoSelecionado.equals("Pepsi")) {
                produto = EProduto.PEPSI;
            } else if (produtoSelecionado.equals("Salgado")) {
                produto = EProduto.SALGADO;
            }
            if (produto != null) {
                jLabelValorEProduto.setText(String.valueOf(produto.getValor()));
            }
        }
    });
       
       Random random = new Random();
       int numeroAleatorio = random.nextInt(9000);
      
       Servico serv = new Servico();
       serv.setCod_servico("" + numeroAleatorio);
      
        // Se for Criado um Novo Uso para o usuario, não será possivel inserir novo servico pois diz que a chave é unique;
        try {
            int IdUltimoUso = new UsoDAO().buscaUltimo(user.getIdUsuario());
            ServicoDAO servicoDAO = new ServicoDAO();
            int idServico = new UsoDAO().buscaIdServico(IdUltimoUso);
            
            if(idServico == 0){
                servicoDAO.inserir(serv); 
                Servico servicoInserido = servicoDAO.buscarPorCodigoServico(serv.getCod_servico());
                Uso uso = new UsoDAO().buscar(IdUltimoUso);
                uso.setServico(servicoInserido);
                new UsoDAO().alterarIdServico(uso);
            }else{
                // Verifica se o serviço já existe no banco de dados
                Servico servicoExistente = servicoDAO.buscar(idServico);
                String codServico = servicoExistente.getCod_servico();

                if (servicoExistente != null) {
                    System.out.println("Já existe um id_servico cadastrado, seu número é " + codServico);

                    Uso uso = new UsoDAO().buscar(IdUltimoUso);
                    uso.setServico(servicoExistente);
                    new UsoDAO().alterarIdServico(uso);
                } else {
                    servicoDAO.inserir(serv);
                    System.out.println("Servico Cadastrado");
                }
            }
            
            
//            // Verifica se o serviço já existe no banco de dados
//            Servico servicoExistente = servicoDAO.buscar(idServico);
//            int idServicoExistente = servicoExistente.getIdServico();
//            String codServico = servicoExistente.getCod_servico();
//            
//            if(servicoExistente != null){
//                System.out.println("Já existe um id_servico cadastrado, seu numero é " + servicoExistente.getCod_servico());
//                
//
//                Uso uso = new UsoDAO().buscar(IdUltimoUso);
//                uso.setServico(servicoExistente);
//                new UsoDAO().alterarIdServico(uso);
//                
//            }else{
//                servicoDAO.inserir(serv);
//                System.out.println("Servico Cadastrado");
////                String produtoSelecionado = (String) jComboBox1.getSelectedItem();
////                if (produtoSelecionado.equals("Coca")) {
////                    serv.addProdutos(EProduto.COCA);
////                } else if (produtoSelecionado.equals("Pepsi")) {
////                    serv.addProdutos(EProduto.PEPSI);
////                } else if (produtoSelecionado.equals("Salgado")) {
////                    serv.addProdutos(EProduto.SALGADO);
////                }   
//                
//            }
//            


        } catch (SQLException ex) {
            Logger.getLogger(ViewSolicitarProduto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ViewSolicitarProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void jBtnSolicitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSolicitarActionPerformed
        
        try {
            int IdUltimoUso = new UsoDAO().buscaUltimo(user.getIdUsuario()); // Busca o Id do ultimo USO do usuario Logado
            ServicoDAO servicoDAO = new ServicoDAO(); // Instancia servicoDAO
            int idServico = new UsoDAO().buscaIdServico(IdUltimoUso); // Pega qual o id_servico
            Servico serv = new ServicoDAO().buscar(idServico); //Puxa o servico que está vinculado ao Ultimo USO do usuario Logado
            
             String produtoSelecionado = (String) jComboBox1.getSelectedItem();
                if (produtoSelecionado.equals("Coca")) {
                    serv.addProdutos(EProduto.COCA);
                } else if (produtoSelecionado.equals("Pepsi")) {
                    serv.addProdutos(EProduto.PEPSI);
                } else if (produtoSelecionado.equals("Salgado")) {
                    serv.addProdutos(EProduto.SALGADO);
                }       
            servicoDAO.inserirProduto(serv);
            JOptionPane.showMessageDialog(null, "Produto Inserido com Sucesso");

        } catch (SQLException ex) {
            Logger.getLogger(ViewSolicitarProduto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ViewSolicitarProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_jBtnSolicitarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSolicitarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSolicitarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSolicitarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSolicitarProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewSolicitarProduto dialog = new ViewSolicitarProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnSolicitar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelValorEProduto;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

private void preencheCombo(ArrayList<EProduto> lista) {
   
        DefaultComboBoxModel dft = (DefaultComboBoxModel) jComboBox1.getModel();
         dft.removeAllElements();
         for(EProduto p :lista){
            dft.addElement(p.getNome());
         }
    }

private Usuario user;

public void setUser(Usuario user) {
    this.user = user;
} 

}
