/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package br.com.lanhouse.view;

import br.com.lanhouse.dao.impl.ClienteDAO;
import br.com.lanhouse.dao.impl.UsoDAO;
import br.com.lanhouse.model.equipamento.Computador;
import br.com.lanhouse.model.pessoas.Cliente;
import br.com.lanhouse.model.pessoas.Usuario;
import br.com.lanhouse.model.servicos.Servico;
import br.com.lanhouse.model.servicos.Uso;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paulo
 */
public class ViewColocarTempo extends javax.swing.JDialog {

    /**
     * Creates new form ViewColocarTempo
     */
    public ViewColocarTempo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextInputLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextInputTempoMinutos = new javax.swing.JTextField();
        jBtnAdicionaTempo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Login");

        jLabel2.setText("Tempo (Minutos)");

        jBtnAdicionaTempo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBtnAdicionaTempo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salvar.png"))); // NOI18N
        jBtnAdicionaTempo.setText("Salvar");
        jBtnAdicionaTempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdicionaTempoActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Login", "Tempo (Minutos)"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextInputTempoMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTextInputLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnPesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnAdicionaTempo)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextInputLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel2))
                            .addComponent(jBtnPesquisar)))
                    .addComponent(jBtnAdicionaTempo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextInputTempoMinutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        try {
            ArrayList<Cliente> lista = new ClienteDAO().buscaPorLogin(jTextInputLogin.getText());
            preencheTabela(lista);
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao consultar "+ex.getMessage());
        }
    }//GEN-LAST:event_jBtnPesquisarActionPerformed

    private void jBtnAdicionaTempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdicionaTempoActionPerformed
        
        String textoTempoMinutos = jTextInputTempoMinutos.getText();
        int qtidadeMinutosTempo = Integer.parseInt(textoTempoMinutos);
        
        int valorInputTempo =  Integer.parseInt(jTextInputTempoMinutos.getText()) ;
        
        int selectedRow = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String idUsuario = (String) model.getValueAt(selectedRow, 0);
        String nome = (String) model.getValueAt(selectedRow, 1);
        String login = (String) model.getValueAt(selectedRow, 2);
        int valorInputIdUsuario = Integer.parseInt(idUsuario);
         
         if (jTable1.getSelectedRow() < 0){
            JOptionPane.showMessageDialog(null, "Selecione uma linha");
        }else{
            
            try {
                //Cliente c2 = new ClienteDAO().buscar(valorInputIdUsuario);
                new UsoDAO().adicionaTempo(new UsoDAO().buscaUltimo(valorInputIdUsuario),valorInputTempo );
                JOptionPane.showMessageDialog(null, "Tempo adicionado com sucesso");
                
            } catch (SQLException ex) {
                Logger.getLogger(ViewColocarTempo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(ViewColocarTempo.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            //Para adicionar tempo ao Uso do cliente, foi necessário encontrar o último id_uso através da busca pelo id_Usuario. O último id_uso do usuário significa a ultima vez que ele eteve logado(incluindo o momento atual).
            //UsoDAO.buscarUltimo()
            //UsoDAO.adicionaTempo()


            
 
//            try {
//                new UsoDAO().buscaUltimo( valorInputTempo);
//            } catch (SQLException ex) {
//                Logger.getLogger(ViewColocarTempo.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (ClassNotFoundException ex) {
//                Logger.getLogger(ViewColocarTempo.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            uso.setIdUsuario(c);
           
//             
//            uso.setIdUsuario(c);
//            uso.setComputador(computador);
//            uso.setQtidadeMinutosTempo(qtidadeMinutosTempo);
//            
//             Servico servico = new Servico();
//             uso.setServico(servico);
//             uso.setDiaLogin(LocalDateTime.now());
//            
//            try {
//                new UsoDAO().alterar(uso);
//                System.out.println("Sucesso");
//            } catch (SQLException ex) {
//                Logger.getLogger(ViewColocarTempo.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (ClassNotFoundException ex) {
//                Logger.getLogger(ViewColocarTempo.class.getName()).log(Level.SEVERE, null, ex);
//            }
             
         }
    }//GEN-LAST:event_jBtnAdicionaTempoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewColocarTempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewColocarTempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewColocarTempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewColocarTempo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewColocarTempo dialog = new ViewColocarTempo(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdicionaTempo;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextInputLogin;
    private javax.swing.JTextField jTextInputTempoMinutos;
    // End of variables declaration//GEN-END:variables

private void preencheTabela(ArrayList<Cliente> lista) throws SQLException, ClassNotFoundException {
        DefaultTableModel dft = (DefaultTableModel) jTable1.getModel();
         while (dft.getRowCount() > 0) {
            dft.removeRow(0);
        }
         UsoDAO uso = new UsoDAO();
         for(Cliente c :lista){
            
            //String tempo = Double.toString(new UsoDAO().buscar(new UsoDAO().buscaUltimo()).getQtidadeMinutosTempo());
            String[] linha = {c.getIdUsuario()+"", c.getNome(), c.getLogin(),uso.buscaTempo(c.getIdUsuario())+""};
            dft.addRow(linha);
        
         }
    }

}
